"""ownership added

Revision ID: 416d060dee0f
Revises: 216f504f61c0
Create Date: 2026-05-26 11:59:45.265739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "416d060dee0f"
down_revision: Union[str, None] = "216f504f61c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_products_owner_id"), "products", ["owner_id"], unique=False
    )
    op.create_foreign_key(None, "products", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_index(op.f("ix_products_owner_id"), table_name="products")
    op.drop_column("products", "owner_id")
    # ### end Alembic commands ###
