"""owner id required

Revision ID: 8c2ffeff2d30
Revises: 416d060dee0f
Create Date: 2026-05-26 14:17:41.441722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c2ffeff2d30"
down_revision: Union[str, None] = "416d060dee0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
